/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ummat.slayer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Locality service. Represents a row in the &quot;Locality&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ummat.slayer.model.impl.LocalityModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ummat.slayer.model.impl.LocalityImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Locality
 * @generated
 */
@ProviderType
public interface LocalityModel
	extends BaseModel<Locality>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a locality model instance should use the {@link Locality} interface instead.
	 */

	/**
	 * Returns the primary key of this locality.
	 *
	 * @return the primary key of this locality
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this locality.
	 *
	 * @param primaryKey the primary key of this locality
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this locality.
	 *
	 * @return the uuid of this locality
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this locality.
	 *
	 * @param uuid the uuid of this locality
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the locality ID of this locality.
	 *
	 * @return the locality ID of this locality
	 */
	public long getLocalityId();

	/**
	 * Sets the locality ID of this locality.
	 *
	 * @param localityId the locality ID of this locality
	 */
	public void setLocalityId(long localityId);

	/**
	 * Returns the region ID of this locality.
	 *
	 * @return the region ID of this locality
	 */
	public long getRegionId();

	/**
	 * Sets the region ID of this locality.
	 *
	 * @param regionId the region ID of this locality
	 */
	public void setRegionId(long regionId);

	/**
	 * Returns the district ID of this locality.
	 *
	 * @return the district ID of this locality
	 */
	public long getDistrictId();

	/**
	 * Sets the district ID of this locality.
	 *
	 * @param districtId the district ID of this locality
	 */
	public void setDistrictId(long districtId);

	/**
	 * Returns the name of this locality.
	 *
	 * @return the name of this locality
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this locality.
	 *
	 * @param name the name of this locality
	 */
	public void setName(String name);

	/**
	 * Returns the active of this locality.
	 *
	 * @return the active of this locality
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this locality is active.
	 *
	 * @return <code>true</code> if this locality is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this locality is active.
	 *
	 * @param active the active of this locality
	 */
	public void setActive(boolean active);

	/**
	 * Returns the company ID of this locality.
	 *
	 * @return the company ID of this locality
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this locality.
	 *
	 * @param companyId the company ID of this locality
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this locality.
	 *
	 * @return the user ID of this locality
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this locality.
	 *
	 * @param userId the user ID of this locality
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this locality.
	 *
	 * @return the user uuid of this locality
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this locality.
	 *
	 * @param userUuid the user uuid of this locality
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this locality.
	 *
	 * @return the create date of this locality
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this locality.
	 *
	 * @param createDate the create date of this locality
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this locality.
	 *
	 * @return the modified date of this locality
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this locality.
	 *
	 * @param modifiedDate the modified date of this locality
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public Locality cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}