/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ummat.slayer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MatriImages service. Represents a row in the &quot;MatriImages&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ummat.slayer.model.impl.MatriImagesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ummat.slayer.model.impl.MatriImagesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MatriImages
 * @generated
 */
@ProviderType
public interface MatriImagesModel
	extends BaseModel<MatriImages>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a matri images model instance should use the {@link MatriImages} interface instead.
	 */

	/**
	 * Returns the primary key of this matri images.
	 *
	 * @return the primary key of this matri images
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this matri images.
	 *
	 * @param primaryKey the primary key of this matri images
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this matri images.
	 *
	 * @return the uuid of this matri images
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this matri images.
	 *
	 * @param uuid the uuid of this matri images
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this matri images.
	 *
	 * @return the ID of this matri images
	 */
	public long getId();

	/**
	 * Sets the ID of this matri images.
	 *
	 * @param id the ID of this matri images
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this matri images.
	 *
	 * @return the group ID of this matri images
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this matri images.
	 *
	 * @param groupId the group ID of this matri images
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this matri images.
	 *
	 * @return the company ID of this matri images
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this matri images.
	 *
	 * @param companyId the company ID of this matri images
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this matri images.
	 *
	 * @return the user ID of this matri images
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this matri images.
	 *
	 * @param userId the user ID of this matri images
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this matri images.
	 *
	 * @return the user uuid of this matri images
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this matri images.
	 *
	 * @param userUuid the user uuid of this matri images
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this matri images.
	 *
	 * @return the user name of this matri images
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this matri images.
	 *
	 * @param userName the user name of this matri images
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this matri images.
	 *
	 * @return the create date of this matri images
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this matri images.
	 *
	 * @param createDate the create date of this matri images
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this matri images.
	 *
	 * @return the modified date of this matri images
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this matri images.
	 *
	 * @param modifiedDate the modified date of this matri images
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the dl entry ID of this matri images.
	 *
	 * @return the dl entry ID of this matri images
	 */
	public long getDlEntryId();

	/**
	 * Sets the dl entry ID of this matri images.
	 *
	 * @param dlEntryId the dl entry ID of this matri images
	 */
	public void setDlEntryId(long dlEntryId);

	@Override
	public MatriImages cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}