/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ummat.travel.webservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DriverDetail service. Represents a row in the &quot;UMMATLife_DriverDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ummat.travel.webservice.model.impl.DriverDetailModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ummat.travel.webservice.model.impl.DriverDetailImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DriverDetail
 * @generated
 */
@ProviderType
public interface DriverDetailModel
	extends BaseModel<DriverDetail>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a driver detail model instance should use the {@link DriverDetail} interface instead.
	 */

	/**
	 * Returns the primary key of this driver detail.
	 *
	 * @return the primary key of this driver detail
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this driver detail.
	 *
	 * @param primaryKey the primary key of this driver detail
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the driver ID of this driver detail.
	 *
	 * @return the driver ID of this driver detail
	 */
	public long getDriverId();

	/**
	 * Sets the driver ID of this driver detail.
	 *
	 * @param driverId the driver ID of this driver detail
	 */
	public void setDriverId(long driverId);

	/**
	 * Returns the user ID of this driver detail.
	 *
	 * @return the user ID of this driver detail
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this driver detail.
	 *
	 * @param userId the user ID of this driver detail
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this driver detail.
	 *
	 * @return the user uuid of this driver detail
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this driver detail.
	 *
	 * @param userUuid the user uuid of this driver detail
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the company ID of this driver detail.
	 *
	 * @return the company ID of this driver detail
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this driver detail.
	 *
	 * @param companyId the company ID of this driver detail
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the driver name of this driver detail.
	 *
	 * @return the driver name of this driver detail
	 */
	@AutoEscape
	public String getDriverName();

	/**
	 * Sets the driver name of this driver detail.
	 *
	 * @param driverName the driver name of this driver detail
	 */
	public void setDriverName(String driverName);

	/**
	 * Returns the age of this driver detail.
	 *
	 * @return the age of this driver detail
	 */
	@AutoEscape
	public String getAge();

	/**
	 * Sets the age of this driver detail.
	 *
	 * @param age the age of this driver detail
	 */
	public void setAge(String age);

	/**
	 * Returns the password of this driver detail.
	 *
	 * @return the password of this driver detail
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this driver detail.
	 *
	 * @param Password the password of this driver detail
	 */
	public void setPassword(String Password);

	/**
	 * Returns the mobile number of this driver detail.
	 *
	 * @return the mobile number of this driver detail
	 */
	@AutoEscape
	public String getMobileNumber();

	/**
	 * Sets the mobile number of this driver detail.
	 *
	 * @param mobileNumber the mobile number of this driver detail
	 */
	public void setMobileNumber(String mobileNumber);

	/**
	 * Returns the email of this driver detail.
	 *
	 * @return the email of this driver detail
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this driver detail.
	 *
	 * @param email the email of this driver detail
	 */
	public void setEmail(String email);

	/**
	 * Returns the gender of this driver detail.
	 *
	 * @return the gender of this driver detail
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this driver detail.
	 *
	 * @param gender the gender of this driver detail
	 */
	public void setGender(String gender);

	/**
	 * Returns the driver photo of this driver detail.
	 *
	 * @return the driver photo of this driver detail
	 */
	@AutoEscape
	public String getDriverPhoto();

	/**
	 * Sets the driver photo of this driver detail.
	 *
	 * @param driverPhoto the driver photo of this driver detail
	 */
	public void setDriverPhoto(String driverPhoto);

	/**
	 * Returns the aadhar number of this driver detail.
	 *
	 * @return the aadhar number of this driver detail
	 */
	@AutoEscape
	public String getAadharNumber();

	/**
	 * Sets the aadhar number of this driver detail.
	 *
	 * @param aadharNumber the aadhar number of this driver detail
	 */
	public void setAadharNumber(String aadharNumber);

	/**
	 * Returns the driving licence ID of this driver detail.
	 *
	 * @return the driving licence ID of this driver detail
	 */
	@AutoEscape
	public String getDrivingLicenceId();

	/**
	 * Sets the driving licence ID of this driver detail.
	 *
	 * @param drivingLicenceId the driving licence ID of this driver detail
	 */
	public void setDrivingLicenceId(String drivingLicenceId);

	/**
	 * Returns the create date of this driver detail.
	 *
	 * @return the create date of this driver detail
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this driver detail.
	 *
	 * @param createDate the create date of this driver detail
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this driver detail.
	 *
	 * @return the modified date of this driver detail
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this driver detail.
	 *
	 * @param modifiedDate the modified date of this driver detail
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public DriverDetail cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}