/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ummat.travel.webservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TravelUser service. Represents a row in the &quot;UMMATLife_TravelUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ummat.travel.webservice.model.impl.TravelUserModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ummat.travel.webservice.model.impl.TravelUserImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TravelUser
 * @generated
 */
@ProviderType
public interface TravelUserModel
	extends BaseModel<TravelUser>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a travel user model instance should use the {@link TravelUser} interface instead.
	 */

	/**
	 * Returns the primary key of this travel user.
	 *
	 * @return the primary key of this travel user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this travel user.
	 *
	 * @param primaryKey the primary key of this travel user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this travel user.
	 *
	 * @return the uuid of this travel user
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this travel user.
	 *
	 * @param uuid the uuid of this travel user
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the travel user ID of this travel user.
	 *
	 * @return the travel user ID of this travel user
	 */
	public long getTravelUserId();

	/**
	 * Sets the travel user ID of this travel user.
	 *
	 * @param travelUserId the travel user ID of this travel user
	 */
	public void setTravelUserId(long travelUserId);

	/**
	 * Returns the travel user uuid of this travel user.
	 *
	 * @return the travel user uuid of this travel user
	 */
	public String getTravelUserUuid();

	/**
	 * Sets the travel user uuid of this travel user.
	 *
	 * @param travelUserUuid the travel user uuid of this travel user
	 */
	public void setTravelUserUuid(String travelUserUuid);

	/**
	 * Returns the user ID of this travel user.
	 *
	 * @return the user ID of this travel user
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this travel user.
	 *
	 * @param userId the user ID of this travel user
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this travel user.
	 *
	 * @return the user uuid of this travel user
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this travel user.
	 *
	 * @param userUuid the user uuid of this travel user
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the company ID of this travel user.
	 *
	 * @return the company ID of this travel user
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this travel user.
	 *
	 * @param companyId the company ID of this travel user
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the travel user name of this travel user.
	 *
	 * @return the travel user name of this travel user
	 */
	@AutoEscape
	public String getTravelUserName();

	/**
	 * Sets the travel user name of this travel user.
	 *
	 * @param travelUserName the travel user name of this travel user
	 */
	public void setTravelUserName(String travelUserName);

	/**
	 * Returns the travel user email of this travel user.
	 *
	 * @return the travel user email of this travel user
	 */
	@AutoEscape
	public String getTravelUserEmail();

	/**
	 * Sets the travel user email of this travel user.
	 *
	 * @param travelUserEmail the travel user email of this travel user
	 */
	public void setTravelUserEmail(String travelUserEmail);

	/**
	 * Returns the travel user phone number of this travel user.
	 *
	 * @return the travel user phone number of this travel user
	 */
	@AutoEscape
	public String getTravelUserPhoneNumber();

	/**
	 * Sets the travel user phone number of this travel user.
	 *
	 * @param travelUserPhoneNumber the travel user phone number of this travel user
	 */
	public void setTravelUserPhoneNumber(String travelUserPhoneNumber);

	/**
	 * Returns the travel user gender of this travel user.
	 *
	 * @return the travel user gender of this travel user
	 */
	@AutoEscape
	public String getTravelUserGender();

	/**
	 * Sets the travel user gender of this travel user.
	 *
	 * @param travelUserGender the travel user gender of this travel user
	 */
	public void setTravelUserGender(String travelUserGender);

	/**
	 * Returns the travel user address of this travel user.
	 *
	 * @return the travel user address of this travel user
	 */
	@AutoEscape
	public String getTravelUserAddress();

	/**
	 * Sets the travel user address of this travel user.
	 *
	 * @param travelUserAddress the travel user address of this travel user
	 */
	public void setTravelUserAddress(String travelUserAddress);

	/**
	 * Returns the travel user profile of this travel user.
	 *
	 * @return the travel user profile of this travel user
	 */
	@AutoEscape
	public String getTravelUserProfile();

	/**
	 * Sets the travel user profile of this travel user.
	 *
	 * @param travelUserProfile the travel user profile of this travel user
	 */
	public void setTravelUserProfile(String travelUserProfile);

	/**
	 * Returns the travel user password of this travel user.
	 *
	 * @return the travel user password of this travel user
	 */
	@AutoEscape
	public String getTravelUserPassword();

	/**
	 * Sets the travel user password of this travel user.
	 *
	 * @param travelUserPassword the travel user password of this travel user
	 */
	public void setTravelUserPassword(String travelUserPassword);

	/**
	 * Returns the country of this travel user.
	 *
	 * @return the country of this travel user
	 */
	public long getCountry();

	/**
	 * Sets the country of this travel user.
	 *
	 * @param country the country of this travel user
	 */
	public void setCountry(long country);

	/**
	 * Returns the state of this travel user.
	 *
	 * @return the state of this travel user
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this travel user.
	 *
	 * @param state the state of this travel user
	 */
	public void setState(String state);

	/**
	 * Returns the district of this travel user.
	 *
	 * @return the district of this travel user
	 */
	public long getDistrict();

	/**
	 * Sets the district of this travel user.
	 *
	 * @param district the district of this travel user
	 */
	public void setDistrict(long district);

	/**
	 * Returns the area of this travel user.
	 *
	 * @return the area of this travel user
	 */
	@AutoEscape
	public String getArea();

	/**
	 * Sets the area of this travel user.
	 *
	 * @param area the area of this travel user
	 */
	public void setArea(String area);

	/**
	 * Returns the pincode of this travel user.
	 *
	 * @return the pincode of this travel user
	 */
	public long getPincode();

	/**
	 * Sets the pincode of this travel user.
	 *
	 * @param pincode the pincode of this travel user
	 */
	public void setPincode(long pincode);

	/**
	 * Returns the create date of this travel user.
	 *
	 * @return the create date of this travel user
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this travel user.
	 *
	 * @param createDate the create date of this travel user
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this travel user.
	 *
	 * @return the modified date of this travel user
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this travel user.
	 *
	 * @param modifiedDate the modified date of this travel user
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public TravelUser cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}