/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ummat_startup_details.model.impl;

import ummat_startup_details.model.MatriUser;

import ummat_startup_details.service.MatriUserLocalServiceUtil;

/**
 * The extended model base implementation for the MatriUser service. Represents a row in the &quot;TNUMMAT_MatriUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MatriUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MatriUserImpl
 * @see MatriUser
 * @generated
 */
public abstract class MatriUserBaseImpl
	extends MatriUserModelImpl implements MatriUser {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a matri user model instance should use the <code>MatriUser</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			MatriUserLocalServiceUtil.addMatriUser(this);
		}
		else {
			MatriUserLocalServiceUtil.updateMatriUser(this);
		}
	}

}